# Generated by Django 5.2.6 on 2025-09-12 08:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Ngày')),
                ('user_input', models.CharField(default='TUYẾT-13749', max_length=100, verbose_name='Người nhập liệu')),
                ('name_of_type', models.CharField(max_length=255, verbose_name='NAME OF TYPE (Mã sản phẩm)')),
                ('pc_plan', models.IntegerField(verbose_name='PC PLAN')),
                ('pro_result', models.IntegerField(verbose_name='PRO RESULT')),
                ('prod_diff', models.IntegerField(blank=True, null=True, verbose_name='PROD 差異 (Chênh lệch)')),
                ('completion_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Đạt tỉ lệ (%)')),
                ('hour_pc_plan', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='HOUR PC PLAN')),
                ('hour_pro', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='HOUR PRO')),
                ('hour_actual', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='HOUR Thực lĩnh')),
                ('out_hour', models.IntegerField(verbose_name='OUT HOUR')),
                ('po_plan_ref', models.IntegerField(verbose_name='PO PLAN-REF')),
                ('pc_plan_ref_2', models.IntegerField(verbose_name='PC PLAN REF 2')),
                ('actuals', models.IntegerField(verbose_name='Kết quả (Actuals)')),
                ('difference', models.IntegerField(blank=True, null=True, verbose_name='Chênh lệch')),
                ('plan_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Đạt tỉ lệ (%) (Plan)')),
                ('total', models.IntegerField(verbose_name='TOTAL')),
                ('ng', models.IntegerField(verbose_name='NG')),
                ('acc_ng', models.IntegerField(verbose_name='ACC NG')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kết quả Sản xuất',
                'verbose_name_plural': 'Kết quả Sản xuất',
                'ordering': ['-date', 'name_of_type'],
            },
        ),
    ]
