# Generated by Django 5.2.6 on 2025-09-15 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionresult',
            name='pc_diff',
            field=models.IntegerField(blank=True, null=True, verbose_name='PC 差異 (Chênh lệch)'),
        ),
    ]
