# Generated by Django 5.2.6 on 2025-09-15 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_data', '0002_productionresult_pc_diff'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionresult',
            name='group',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='GROUP'),
        ),
        migrations.AddField(
            model_name='productionresult',
            name='line',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='LINE'),
        ),
        migrations.AddField(
            model_name='productionresult',
            name='shift',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='SHIFT'),
        ),
        migrations.AddField(
            model_name='productionresult',
            name='to_assess',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='TO ASSESS'),
        ),
        migrations.AlterField(
            model_name='productionresult',
            name='name_of_type',
            field=models.CharField(max_length=255, verbose_name='Mã sản phẩm (MODEL)'),
        ),
    ]
