# Generated by Django 5.2.6 on 2025-09-15 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_data', '0003_productionresult_group_productionresult_line_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionresult',
            name='out_hour',
        ),
        migrations.AddField(
            model_name='productionresult',
            name='qty_hour',
            field=models.IntegerField(blank=True, null=True, verbose_name='QTY/HOUR'),
        ),
    ]
