# Generated by Django 5.2.6 on 2025-09-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_data', '0004_remove_productionresult_out_hour_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productionresult',
            old_name='hour_pro',
            new_name='hour_pro_plan',
        ),
        migrations.RemoveField(
            model_name='productionresult',
            name='pro_result',
        ),
        migrations.AddField(
            model_name='productionresult',
            name='pro_plan',
            field=models.IntegerField(blank=True, null=True, verbose_name='PRO PLAN'),
        ),
        migrations.AddField(
            model_name='productionresult',
            name='result',
            field=models.IntegerField(blank=True, null=True, verbose_name='RESULT'),
        ),
    ]
