# Generated by Django 5.2.6 on 2025-09-17 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_data', '0005_rename_hour_pro_productionresult_hour_pro_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionresult',
            name='input_actual',
            field=models.IntegerField(blank=True, null=True, verbose_name='Input actual'),
        ),
        migrations.AddField(
            model_name='productionresult',
            name='input_material',
            field=models.IntegerField(blank=True, null=True, verbose_name='Input Material'),
        ),
        migrations.AddField(
            model_name='productionresult',
            name='output',
            field=models.IntegerField(blank=True, null=True, verbose_name='Output'),
        ),
        migrations.AddField(
            model_name='productionresult',
            name='output_before',
            field=models.IntegerField(blank=True, null=True, verbose_name='Output Before'),
        ),
        migrations.AddField(
            model_name='productionresult',
            name='person_actual',
            field=models.IntegerField(blank=True, null=True, verbose_name='Person Actual'),
        ),
        migrations.AddField(
            model_name='productionresult',
            name='person_diff',
            field=models.IntegerField(blank=True, null=True, verbose_name='Person Diff'),
        ),
        migrations.AddField(
            model_name='productionresult',
            name='person_standard',
            field=models.IntegerField(blank=True, null=True, verbose_name='Person Standard'),
        ),
        migrations.AlterField(
            model_name='productionresult',
            name='ng',
            field=models.IntegerField(blank=True, null=True, verbose_name='NG'),
        ),
    ]
