# Generated by Django 5.2.6 on 2025-09-17 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_data', '0006_productionresult_input_actual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionresult',
            name='acc_ng',
            field=models.IntegerField(blank=True, null=True, verbose_name='ACC NG'),
        ),
        migrations.AlterField(
            model_name='productionresult',
            name='total',
            field=models.IntegerField(blank=True, null=True, verbose_name='TOTAL'),
        ),
    ]
