# Generated by Django 5.2.6 on 2025-09-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_data', '0007_alter_productionresult_acc_ng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionresult',
            name='actuals',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kết quả (Actuals)'),
        ),
        migrations.AlterField(
            model_name='productionresult',
            name='hour_actual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='HOUR Thực lĩnh'),
        ),
        migrations.AlterField(
            model_name='productionresult',
            name='hour_pc_plan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='HOUR PC PLAN'),
        ),
        migrations.AlterField(
            model_name='productionresult',
            name='hour_pro_plan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='HOUR PRO'),
        ),
        migrations.AlterField(
            model_name='productionresult',
            name='pc_plan',
            field=models.IntegerField(blank=True, null=True, verbose_name='PC PLAN'),
        ),
        migrations.AlterField(
            model_name='productionresult',
            name='pc_plan_ref_2',
            field=models.IntegerField(blank=True, null=True, verbose_name='PC PLAN REF 2'),
        ),
        migrations.AlterField(
            model_name='productionresult',
            name='po_plan_ref',
            field=models.IntegerField(blank=True, null=True, verbose_name='PO PLAN-REF'),
        ),
    ]
