# Generated by Django 5.2.6 on 2025-09-26 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_data', '0009_alter_productionresult_user_input_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Mã Group')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên Group')),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã Line')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên Line')),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='Mã Model')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên Model')),
            ],
        ),
        migrations.AlterModelOptions(
            name='productionresult',
            options={'ordering': ['-date', 'product_model__code'], 'verbose_name': 'Kết quả Sản xuất', 'verbose_name_plural': 'Kết quả Sản xuất'},
        ),
        migrations.RemoveField(
            model_name='productionresult',
            name='name_of_type',
        ),
        migrations.AlterField(
            model_name='productionresult',
            name='difference',
            field=models.IntegerField(blank=True, null=True, verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='productionresult',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production_data.group', verbose_name='Group'),
        ),
        migrations.AddField(
            model_name='group',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='production_data.line'),
        ),
        migrations.AlterField(
            model_name='productionresult',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production_data.line', verbose_name='Line'),
        ),
        migrations.AddField(
            model_name='productionresult',
            name='product_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production_data.productmodel', verbose_name='Model'),
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ca')),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='production_data.line')),
            ],
        ),
        migrations.AlterField(
            model_name='productionresult',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production_data.shift', verbose_name='Ca'),
        ),
    ]
