# Generated by Django 5.2.6 on 2025-09-26 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_data', '0010_group_line_productmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã nhóm model')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên nhóm')),
            ],
        ),
        migrations.AddField(
            model_name='productmodel',
            name='group_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production_data.productgroup', verbose_name='Nhóm Model'),
        ),
    ]
