# Generated by Django 5.2.6 on 2025-09-26 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production_data', '0011_productgroup_productmodel_group_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='line',
        ),
    ]
